services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
    - /opt/docker/postgres-data:/var/lib/postgresql

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#    - 8080:8080
